detectors:
  DuplicateMethodCall:
    allow_calls:
      - self.class
  UncommunicativeMethodName:
    accept:
      - x
      - y
  UncommunicativeParameterName:
    accept:
      - x
      - y
  UncommunicativeVariableName:
    accept:
      - _
      - x
      - y
  UnusedPrivateMethod:
    enabled: false # Disabled by default.
  UtilityFunction:
    public_methods_only: true # Disabled by default.

directories:
  app/channels/application_cable:
    IrresponsibleModule:
      enabled: false
  app/components:
    IrresponsibleModule:
      enabled: false
  app/controllers:
    IrresponsibleModule:
      enabled: false
  app/helpers:
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    LongParameterList:
      enabled: false
  app/mailers:
    IrresponsibleModule:
      enabled: false
  app/views:
    IrresponsibleModule:
      enabled: false
    TooManyMethods:
      enabled: false
    UtilityFunction:
      enabled: false
  test:
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false

exclude_paths:
  - db/migrate/*
  - test/**/*
  - lib/templates/**/*
