plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

inherit_gem:
  gemwork: lib/rubocop/.rubocop-rails.yml

Naming/MethodParameterName:
  AllowedNames:
    - as
    - "on"
    - "x"
    - "y"

Style/GuardClause:
  # Guard clauses are great, but it's OK to use straight conditionals if they
  # tell the story better.
  Enabled: false

Style/IfUnlessModifier:
  # Still prefer the modifier form of conditionals in general, just don't
  # require it in all cases. It can be hard to reliably spot a modifier at the
  # end of a long line. And, unfortunately, this cop will always require the
  # modifier form if the resulting line can fit within Layout/LineLength's "Max"
  # setting.
  Enabled: false

Style/EmptyClassDefinition:
  # Prefer using single-line constant definition for StandardError classes
  # (only). e.g.
  #   class MyModel < ApplicationRecord; end # Good
  #   MyModel = Class.new(ApplicationRecord) # Bad
  #
  #   Error = Class.new(StandardError)       # Good
  #   class Error < StandardError; end       # Bad
  EnforcedStyle: class_keyword
  AllowedParentClasses:
    - StandardError
