require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails

inherit_gem:
  gemwork: lib/rubocop/.rubocop-rails.yml

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - bin/bundle
    - db/schema.rb
    - lib/templates/**/*

Layout/LineLength:
  Exclude:
    - Gemfile
    - config/environments/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - db/migrate/*.rb

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

Rails/ApplicationController:
  Exclude:
    - app/controllers/ui_portal/**/*

Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - app/helpers/**/*
    - app/mailers/**/*
    - app/models/concerns/**/*
    - db/**/*
    - test/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - config.ru
    - bin/*

Style/HashAsLastArrayItem:
  Exclude:
    - test/**/*
