require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

inherit_gem:
  gemwork: lib/rubocop/.rubocop-rails.yml

AllCops:
  TargetRubyVersion: 3.4

Layout/FirstMethodArgumentLineBreak:
  AllowedMethods:
    - t
    - safe_join

Metrics/MethodLength:
  AllowedMethods:
    - create
    - update
  Exclude:
    - db/migrate/*.rb

Naming/MethodParameterName:
  AllowedNames:
    - "on"
    - "x"
    - "y"

Rails/ApplicationController:
  Exclude:
    - app/controllers/ui_portal/**/*
